// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Reservas.Infraestructura.Persistencia;

#nullable disable

namespace Reservas.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ReservasDbContext))]
    [Migration("20260930065453_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reservas.Dominio.Gestion.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoGestion")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)")
                        .HasColumnName("codigo_gestion");

                    b.Property<int>("Comensales")
                        .HasColumnType("integer")
                        .HasColumnName("comensales");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<NpgsqlRange<DateTime>>("Intervalo")
                        .HasColumnType("tstzrange")
                        .HasColumnName("periodo");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.PrimitiveCollection<Guid[]>("_mesaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("mesa_ids");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reservas");

                    b.HasIndex("CodigoGestion")
                        .IsUnique()
                        .HasDatabaseName("ix_reservas_codigo_gestion");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("ix_reservas_negocio_id");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Cierre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.Property<short?>("Turno")
                        .HasColumnType("smallint")
                        .HasColumnName("turno");

                    b.HasKey("Id")
                        .HasName("pk_cierres");

                    b.HasIndex("NegocioId", "Fecha")
                        .HasDatabaseName("ix_cierres_negocio_id_fecha");

                    b.ToTable("cierres", (string)null);
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Dia")
                        .HasColumnType("smallint")
                        .HasColumnName("dia");

                    b.Property<TimeOnly>("Fin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fin");

                    b.Property<TimeOnly>("Inicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("inicio");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalo_minutos");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.Property<short>("Turno")
                        .HasColumnType("smallint")
                        .HasColumnName("turno");

                    b.HasKey("Id")
                        .HasName("pk_horarios");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("ix_horarios_negocio_id");

                    b.ToTable("horarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_horarios_fin", "fin >= inicio");

                            t.HasCheckConstraint("ck_horarios_intervalo", "intervalo_minutos BETWEEN 5 AND 120");
                        });
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_maxima");

                    b.Property<int>("CapacidadMinima")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_minima");

                    b.Property<bool>("EsCombinable")
                        .HasColumnType("boolean")
                        .HasColumnName("es_combinable");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sala_id");

                    b.HasKey("Id")
                        .HasName("pk_mesas");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("ix_mesas_negocio_id");

                    b.HasIndex("SalaId")
                        .HasDatabaseName("ix_mesas_sala_id");

                    b.ToTable("mesas", null, t =>
                        {
                            t.HasCheckConstraint("ck_mesas_capacidad", "capacidad_minima >= 1 AND capacidad_minima <= capacidad_maxima AND capacidad_maxima <= 30");
                        });
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_salas");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("ix_salas_negocio_id");

                    b.ToTable("salas", (string)null);
                });

            modelBuilder.Entity("Reservas.Dominio.Negocios.Negocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("zona");

                    b.HasKey("Id")
                        .HasName("pk_negocios");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_negocios_slug");

                    b.ToTable("negocios", (string)null);
                });

            modelBuilder.Entity("Reservas.Infraestructura.Persistencia.OcupacionMesaEntidad", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("negocio_id");

                    b.Property<NpgsqlRange<DateTime>>("Periodo")
                        .HasColumnType("tstzrange")
                        .HasColumnName("periodo");

                    b.HasKey("ReservaId", "MesaId")
                        .HasName("pk_ocupaciones_mesa");

                    b.HasIndex("MesaId")
                        .HasDatabaseName("ix_ocupaciones_mesa_mesa_id");

                    b.HasIndex("NegocioId")
                        .HasDatabaseName("ix_ocupaciones_mesa_negocio_id");

                    b.ToTable("ocupaciones_mesa", (string)null);
                });

            modelBuilder.Entity("Reservas.Dominio.Gestion.Reserva", b =>
                {
                    b.HasOne("Reservas.Dominio.Negocios.Negocio", null)
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_negocios_negocio_id");

                    b.OwnsOne("Reservas.Dominio.Gestion.DatosCliente", "Cliente", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("cliente_email");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("cliente_nombre");

                            b1.Property<string>("Telefono")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("cliente_telefono");

                            b1.HasKey("ReservaId");

                            b1.ToTable("reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId")
                                .HasConstraintName("fk_reservas_reservas_id");
                        });

                    b.Navigation("Cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Cierre", b =>
                {
                    b.HasOne("Reservas.Dominio.Negocios.Negocio", null)
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cierres_negocios_negocio_id");
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Horario", b =>
                {
                    b.HasOne("Reservas.Dominio.Negocios.Negocio", null)
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horarios_negocios_negocio_id");
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Mesa", b =>
                {
                    b.HasOne("Reservas.Dominio.Negocios.Negocio", null)
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mesas_negocios_negocio_id");

                    b.HasOne("Reservas.Dominio.Locales.Sala", null)
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mesas_salas_sala_id");
                });

            modelBuilder.Entity("Reservas.Dominio.Locales.Sala", b =>
                {
                    b.HasOne("Reservas.Dominio.Negocios.Negocio", null)
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salas_negocios_negocio_id");
                });

            modelBuilder.Entity("Reservas.Dominio.Negocios.Negocio", b =>
                {
                    b.OwnsOne("Reservas.Dominio.Negocios.PoliticasReserva", "Politicas", b1 =>
                        {
                            b1.Property<Guid>("NegocioId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("AntelacionMinima")
                                .HasColumnType("interval")
                                .HasColumnName("politicas_antelacion_minima");

                            b1.Property<int>("DiasMaximosAntelacion")
                                .HasColumnType("integer")
                                .HasColumnName("politicas_dias_maximos_antelacion");

                            b1.Property<TimeSpan>("DuracionEstandar")
                                .HasColumnType("interval")
                                .HasColumnName("politicas_duracion_estandar");

                            b1.Property<int>("MaxComensalesOnline")
                                .HasColumnType("integer")
                                .HasColumnName("politicas_max_comensales_online");

                            b1.HasKey("NegocioId");

                            b1.ToTable("negocios");

                            b1.WithOwner()
                                .HasForeignKey("NegocioId")
                                .HasConstraintName("fk_negocios_negocios_id");
                        });

                    b.Navigation("Politicas")
                        .IsRequired();
                });

            modelBuilder.Entity("Reservas.Infraestructura.Persistencia.OcupacionMesaEntidad", b =>
                {
                    b.HasOne("Reservas.Dominio.Locales.Mesa", null)
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ocupaciones_mesa_mesas_mesa_id");

                    b.HasOne("Reservas.Dominio.Gestion.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ocupaciones_mesa_reservas_reserva_id");
                });
#pragma warning restore 612, 618
        }
    }
}
